import "@/styles/globals.css";

import React from "react";
import { Toaster } from "react-hot-toast";

// TODO: add metadata
export const metadata = {
  title: `Next.js`,
  description: `Generated by Next.js`,
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
